[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "bbb"
version = "0.1"
description = "Bilingual Book Builder"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bertalign",
    "fast-ebook>=0.2.0",
    "bs4>=0.0.2",
    "numpy>=2.4.6",
    # "numba>=0.65.1",
    # "faiss-gpu>=1.14.3",
    # "googletrans>=4.0.2",
    # "sentence-splitter>=1.4",
    # "sentence-transformers>=5.6.0",
]

[project.optional-dependencies]
cpu = ["bertalign[cpu] @ git+https://github.com/kerivin/bertalign.git"]
gpu = ["bertalign[gpu] @ git+https://github.com/kerivin/bertalign.git"]

[project.scripts]
bbb = "bbb.cli:main"

[tool.setuptools.packages.find]
include = ["bbb*"]