[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "bbb"
version = "0.1"
description = "Bilingual Book Builder"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ebooklib>=0.20",
    "bs4>=0.0.2",
    "numpy>=2.4.6",
    "tqdm"
]

[project.optional-dependencies]
cpu = ["bertalign[cpu] @ git+https://github.com/kerivin/bertalign.git"]
gpu = ["bertalign[gpu] @ git+https://github.com/kerivin/bertalign.git"]

[project.scripts]
bbb = "bbb.cli:main"

[tool.setuptools.packages.find]
include = ["bbb*"]